### ISSUE TITLE
 SeqClean on transcripts failed, check logfiles

### ISSUE THREAD

**Issue by Sabryr** [nextgenusfs/funannotate#568] opened 2021-03-09 12:29 UTC
We are getting the error "SeqClean on transcripts failed, check logfiles" for Pacbio hifi reads. Apart from the the error thare is notthing elase in the log files to locate issue. Thank you in advance, for any assitnace or a way to get more debug info. 
```
[03/09/21 12:11:24]: OS: CentOS Linux 7, 64 cores, ~ 792 GB RAM. Python: 3.7.10
[03/09/21 12:11:24]: Running 1.8.3
[03/09/21 12:11:28]: Input reads: (None, None, None)
[03/09/21 12:11:28]: Quality trimmed reads: (None, None, None)
[03/09/21 12:11:28]: Normalized reads: (None, None, None)
[03/09/21 12:11:28]: No short reads detected, Trinity will be skipped.
[03/09/21 12:11:28]: Long reads: ('/cluster/projects/nn9825k/admin/data/C_carnea_iso-seq_sample.fastq', None, None)
[03/09/21 12:11:28]: Processing long reads: converting to fasta and running SeqClean
[03/09/21 12:11:30]: /cluster/projects/nn9825k/admin/funannotate/opt/pasa-2.4.1/bin/seqclean iso-seq.fasta -c 2
[03/09/21 12:11:35]: seqclean running options: 
seqclean iso-seq.fasta -c 2
 Standard log file: seqcl_iso-seq.fasta.log
 Error log file:    err_seqcl_iso-seq.fasta.log
 Using 2 CPUs for cleaning
-= Rebuilding iso-seq.fasta cdb index =-
 Launching actual cleaning process:
 psx -p 2  -n 1000  -i iso-seq.fasta -d cleaning -C '/cluster/projects/nn9825k/admin/data/iso-seq.fasta:ANLMS100:::11:0' -c '/cluster/projects/nn9825k/admin/funannotate/opt/pasa-2.4.1/bin/seqclean.psx'
Collecting cleaning reports

**************************************************
Sequences analyzed:      2500
-----------------------------------
                   valid:      2500  (53 trimmed)
                 trashed:         0
**************************************************
Output file containing only valid and trimmed sequences: iso-seq.fasta.clean
For trimming and trashing details see cleaning report  : iso-seq.fasta.cln
--------------------------------------------------
seqclean (iso-seq.fasta) finished on machine x86_64-conda-linux-gnu
 in /cluster/projects/nn9825k/admin/data, without a detectable error.

[03/09/21 12:11:36]: Long reads FASTA format: ('/cluster/projects/nn9825k/admin/data/C_carnea_iso-seq_sample.fastq', None, None)
[03/09/21 12:11:36]: Long SeqCleaned reads: ('BM3-fun_test/training/iso-seq.fasta.clean', None, None)
[03/09/21 12:11:36]: SeqClean on transcripts failed, check logfiles
```

**Comment by nextgenusfs** [comment] 2021-03-12 01:36
What command did you run?

**Comment by nextgenusfs** [comment] 2021-03-12 01:38
Looks like it ran properly -- probably a bug in the QC check at the end of this routine related to not having any Illumina data -- but need to check to see if I can reproduce.

**Comment by nextgenusfs** [comment] 2021-03-12 06:33
Okay, I was able to duplicate locally.  I just pushed a fix, you can install the latest from the git repo with pip.  Let me know if problem is fixed.

**Comment by Sabryr** [comment] 2021-03-12 11:16
Thank you very much for fixing. I will try to install from Git repo, it was an uphill battle getting this installed with conda in the first round,

**Comment by nextgenusfs** [comment] 2021-03-12 17:05
Yes I know installing is not fun -- you can just upgrade funannotate from that Conda environment with pip -- all other dependencies are the same.

**Closed** 2021-04-17 21:55 UTC
