### ISSUE TITLE
Interproscan5 

### ISSUE THREAD

**Issue by Dikaryotic** [nextgenusfs/funannotate#383] opened 2020-02-18 21:46 UTC
**Are you using the latest release?**
v1.7.3

**Describe the bug**
I've run interproscan5 separately and incorporated it via funannotate annotate --iprscan xx.xml. I was checking the updates and issue requests to see if anyone was having trouble with interproscan5 noticed in the latest update you made this comment "add --debug flag to funannotate iprscan -- there is potentially still an issue here combining results from the newest release of Interproscan -- I need some intermediate results to see what the problem is"

I have my current iprscan files, as well as some older output from previous runs if any of that would be helpful. 

The funannotate-annotate.log file shows the following error: 
```
Parsing InterProScan5 XML file
[02/18/20 16:34:42]: /home/osboxes/Desktop/Programs/Miniconda3/envs/Funannotate/bin/python /home/osboxes/D$
[02/18/20 16:34:42]: Traceback (most recent call last):
  File "/home/osboxes/Desktop/Programs/Miniconda3/envs/Funannotate/lib/python2.7/site-packages/funannotate$
    for _, elem in tree:
  File "<string>", line 91, in next
cElementTree.ParseError: mismatched tag: line 6, column 4
```

**What command did you issue?**
funannotate annotate -i LEN2_R2/ -s "xxx" --isolate LEN2 --eggnog LEN2-eggnog.annotations --antismash LEN2-Antismash.gbk --busco_db basidiomycota --iprscan LEN2-IPR.xml --phobius LEN2-phobius.txt

**OS/Install Information**
funannotate annotate -i LEN2_R2/ -s "Lentinula novae-zelandiae" --isolate LEN2 --eggnog LEN2-eggnog.annotations --antismash LEN2-Antismash.gbk --busco_db basidiomycota --iprscan LEN2-IPR.xml --phobius LEN2-phobius.txt

**Comment by nextgenusfs** [comment] 2020-02-18 22:04
Thanks Chris.  Yes there is a known bug with how funannotate runs interproscan, I'm not sure yet what version of interproscan is effected, I know that I'm running `interproscan-5.31-70.0` which still works (admittedly I should upgrade, but it takes so long to setup/download....). 

What version of interproscan do you have?

The issue seems to be that the XML header changed at some point from the output and my "hack" at recombining the data after the run apparently didn't deal with this change very well.  @atiweb is also looking into this.  But if you have some more information on versions and what the XML headers look like that could be helpful.

**Comment by nextgenusfs** [comment] 2020-02-18 22:09
So if you look here: https://github.com/ebi-pf-team/interproscan/wiki/OutputFormats#example-output-2 this is what the format used to be.  But now it seems like the <protein matches> tag is written on the same line as the header.... So if you could just paste the first 10 lines or so that would probably be helpful.

Maybe we should switch to JSON format, would be easier to parse.....

**Comment by Dikaryotic** [comment] 2020-02-18 22:10
I'm using interproscan-5.40.77.0, it seems like this has only popped up since I upgraded :P Which I was loath to do because it takes so long too! Here's the first full entry from a recent iprscan5 run.

head -50 B17-IPR.xml 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<protein-matches xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5">
    <sequence md5="a5ed77a8c684e67b8e26ec7108ab3b1a">MAGQVATMNEILRMCEDVRGTKFDVKYNSREDVVARMSSAPEKAIENFFMENYLAIIDGDADLKRPLNLNELVDVKPMGVQEYLLKWWDIDRHIFRPFDDGKKEKRRKDLSGKVVKEISERREDGRHYTENINVLVSTTASLSTNPSLVPSYNLRLLPFTISAPLSFLEEQRKVEDEWKKGRDRVRERLLEGIEERRKRAREDKEGEGISADATLDSQNRPHITRKLRNKMGTPPPMTPLGSQLGSAAVSSAATAISSGSGGNGGSGALGANPGGGSASGPGVGGSASTAGGRRRPKGSGTHQSQAIGGLGKSLAMLNALKDTEIEADLGEI</sequence>
    <xref id="FUN_006580-T1" name="FUN_006580-T1 FUN_006580"/>
    <matches>
      <mobidblite-match>
        <signature ac="mobidb-lite" desc="consensus disorder prediction" name="disorder_prediction">
          <signature-library-release library="MOBIDB_LITE" version="2.0"/>
        </signature>
        <model-ac>mobidb-lite</model-ac>
        <locations>
          <mobidblite-location sequence-feature="" start="197" end="308">
            <location-fragments>
              <mobidblite-location-fragment start="197" end="308" dc-status="CONTINUOUS"/>
            </location-fragments>
          </mobidblite-location>
        </locations>
      </mobidblite-match>
      <mobidblite-match>
        <signature ac="mobidb-lite" desc="consensus disorder prediction" name="disorder_prediction">
          <signature-library-release library="MOBIDB_LITE" version="2.0"/>
        </signature>
        <model-ac>mobidb-lite</model-ac>
        <locations>
          <mobidblite-location sequence-feature="Polar" start="239" end="265">
            <location-fragments>
              <mobidblite-location-fragment start="239" end="265" dc-status="CONTINUOUS"/>
            </location-fragments>
          </mobidblite-location>
        </locations>
      </mobidblite-match>
    </matches>
  </protein>
  <protein>
    <sequence md5="c75b1af5919accc2bde84c6e03ade7be">MGLLSTPTSSPPPSSPPTSSKSPPPPPQSQPQPQPHLHPHLHLQPQPQSTRMRRHLPRLHPPQPNPFYRQHGSQNSREIRRRFGARVQVVPEAAVLLQYDAVLGRWTCVDRVEADKGGSMMKFVKASGNASQLLIAQAGGWVAVYTVQMREGKLRLVRTTARKLDLAEQKRYDVRVKSASAYIPPYIYLPAPPSSPPLPHGTTPKSPPSPVPSSTPPNTSPASSPQPSGTQTNLHYIPSILLLSPLNPPPS</sequence>

**Comment by nextgenusfs** [comment] 2020-02-18 22:15
Something seems to be not quite right there with your head/xml command, should look like:
```
$ head -n 3 iprscan.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<protein-matches xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5">
    <protein>
```
This is what `interproscan-5.31-70.0` first 3 lines looks like.

**Comment by Dikaryotic** [comment] 2020-02-18 22:53
I've just had a look at three of my newer ones and one of my older ones, the newer ones all share the same format, where as the older one is identical to the one you posted. 

My older run:
head -n 3 iprscan.xml 
<protein-matches xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5" interProScanVersion="5.38-76.0">
  <protein>
    <sequence md5="364a8eabd34c0e7544ff0c2f2f3ce35f">MASELLSALRTQDFRNHYIQFGRWYSAHRPLVQRTINIAFIVYVLGSTFRGLSGKGGSSRSNKSRKGKGSKAGKDDDDNRSTRVAVDSVFYQRLGAILRIVIPSIRSKEALLLVTHSSLLVLRTAISLYVAALDGRIVASLVRAQPMQFFLNILRWLCVAIPATWTNSWLSYVQNKLTIAYRTRL

Another example of a newer one:
==> W126-IPR.xml <==
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<protein-matches xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5">
    <sequence **md5="dcec934236fa12a59054f96ce1dff20a">MDVIVHAGNKE**

**Comment by atiweb** [comment] 2020-02-18 23:12
Hi to everyone, @Dikaryotic you say you are using interproscan-5.40.77.0, but in https://www.ebi.ac.uk/interpro/download/ the last version available is InterProScan 5.39-77.0

I have been upgrading interproscan, and from version InterProScan 5.38-77.0 the same error have been happening. 
This error:
`Parsing InterProScan5 XML file
[02/18/20 16:34:42]: /home/osboxes/Desktop/Programs/Miniconda3/envs/Funannotate/bin/python /home/osboxes/D$
[02/18/20 16:34:42]: Traceback (most recent call last):
  File "/home/osboxes/Desktop/Programs/Miniconda3/envs/Funannotate/lib/python2.7/site-packages/funannotate$
    for _, elem in tree:
  File "<string>", line 91, in next
cElementTree.ParseError: mismatched tag: line 6, column 4`

The cause is some missing protein tags on generated xml file.

About the speed of interproscan, is slow, yes, very slow, is hard to tune for your system, be sure you have enough available free RAM and CPU, read and set for you your interproscan.properties file.
If happen you run out of ram and the swap is used, it can take a lot more of time.
For example, annotating a genome of fungi, lets say, about 40 Mb of size, with 8 CPU and 16 Gb of RAM can take almost 2 day.
With 24 CPU and more than 40 Gb of ram take about 5 of 6 hours.
All these is relative, obviously.
Read https://github.com/nextgenusfs/funannotate/issues/362 if you like about more information about this issue. We are working on solve this./
Greettings.
PD: By the way, interproscan have to a lots of dependencies that need manual tunning, install and configuration.

**Comment by Dikaryotic** [comment] 2020-02-18 23:18
ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.40-77.0/

I'm less concerned about the run time and more about how long it takes to install and update the thing. Generally annotation with funannotate iprscan runs in less than 5 hours on my cluster, using 15 cpus and 50G ram, which is fine enough for my purposes.

**Comment by atiweb** [comment] 2020-02-18 23:27
Thanks @Dikaryotic, it appear to be that have been a major change of format from version InterProScan-5.39-77.0 to interproscan-5.40.77.0.

**Comment by nextgenusfs** [comment] 2020-02-19 01:53
Thanks for all the info.  What I need in order to fix funannotate is to know what the XML format is going to be from the different versions.  @Dikaryotic would you be able to run this on your cluster with the attached protein FASTA file?  Command should be:
```
interproscan.sh -i test.proteins.fasta -d . -b test-iprscan -f XML,JSON -goterms -pa
```
If you could attached the resulting XML and JSON files that will be helpful.  I'm including JSON here as that might be a lot easier to parse and potentially more stable.  But all depends on how much they have changed the format. 

[test.proteins.fasta.zip](https://github.com/nextgenusfs/funannotate/files/4222713/test.proteins.fasta.zip)

**Comment by hyphaltip** [comment] 2020-02-19 02:45
I’ll try todo it too. We have several versions installed on cluster.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by nextgenusfs** [comment] 2020-02-19 19:16
Attached are results (both XML and JSON) on this sample test set using `interproscan-version="5.31-70.0"`.
[iprscan-5.31-70.0.zip](https://github.com/nextgenusfs/funannotate/files/4226878/iprscan-5.31-70.0.zip)

**Comment by Dikaryotic** [comment] 2020-02-20 02:39
Here are the results using interproscan-5.40.77.0

head -n 10 test-iprscan.*
==> test-iprscan.json <==
{
 "interproscan-version": "5.40-77.0",
"results": [ {
  "sequence" : "MNTVRSFWVGWGALCTAGGGAYFFAKRSINTDRRQRREEQSKRQQMQDHLERSATSTSSSLTDKTTRTVITGASKDKGAQTERLG",
  "md5" : "98251b566d147a1e5583bfa4cf566611",
  "matches" : [ {
    "signature" : {
      "accession" : "mobidb-lite",
      "name" : "disorder_prediction",
      "description" : "consensus disorder prediction",

==> test-iprscan.xml <==
<?xml version="1.0" encoding="UTF-8"?><protein-matches xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5" interProScanVersion="5.40-77.0">
  <protein>
    <sequence md5="98251b566d147a1e5583bfa4cf566611">MNTVRSFWVGWGALCTAGGGAYFFAKRSINTDRRQRREEQSKRQQMQDHLERSATSTSSSLTDKTTRTVITGASKDKGAQTERLG</sequence>
    <xref id="GN2_000029-T1" name="GN2_000029-T1 GN2_000029"/>
    <matches>
      <hmmer3-match evalue="2.1E-21" score="75.4">
        <signature ac="PF15932" desc="Domain of unknown function (DUF4748)" name="DUF4748">
          <entry ac="IPR031833" desc="Protein of unknown function DUF4748" name="DUF4748" type="FAMILY"/>
          <signature-library-release library="PFAM" version="32.0"/>
        </signature>

**Comment by nextgenusfs** [comment] 2020-02-20 02:45
Thanks @Dikaryotic -- can you zip up the two output files and attach?

**Comment by nextgenusfs** [comment] 2020-02-20 02:48
If you use three backticks you can format like I did above -- code snippets etc.

**Comment by Dikaryotic** [comment] 2020-02-20 02:50
[test_iprscan.zip](https://github.com/nextgenusfs/funannotate/files/4228532/test_iprscan.zip)

Heh thanks :)

**Comment by atiweb** [comment] 2020-02-20 13:06
Attached are results (both XML and JSON) on this sample test set using interproscan-version="InterProScan-5.39-77.0".

[test-iprscan_on_InterProScan-5.39-77.0.zip](https://github.com/nextgenusfs/funannotate/files/4230821/test-iprscan_on_InterProScan-5.39-77.0.zip)

**Comment by nextgenusfs** [comment] 2020-02-21 05:27
Okay, thanks everybody.  I just elected to combine with ElementTree as it seemed relatively fast enough and it reads the tags properly regardless of what line the <protein matches> is written on. Would you guys be able to test the code in master? @atiweb the current tip should also have your other fixes in them.

**Comment by atiweb** [comment] 2020-02-21 15:05
Testing now iprscan:

funannotate iprscan -i test.proteins.fasta -n 100 \
> -o testOKOKOK.funannotate.xml \
> --debug \
> --method local \
> --cpus 7 \
> --iprscan_path /mnt/sdb/funannotate/interproscan/interproscan-5.39-77.0/interproscan.sh
Running InterProScan5 on 295 proteins
Important: you need to manually configure your interproscan.properties file for embedded workers.
Will try to launch 7 interproscan processes, adjust -c,--cpus for your system
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/funannotate/aux_scripts/iprscan-local.py", line 359, in <module>
    combine_xml(final_list, finalOut)
  File "/usr/local/lib/python2.7/dist-packages/funannotate/aux_scripts/iprscan-local.py", line 50, in combine_xml
    tree._setroot(first)
NameError: global name 'tree' is not defined

**Comment by nextgenusfs** [comment] 2020-02-21 15:42
Ah, oops.  Thanks for checking so fast, looks like forgot to initialize tree, can you check latest commit?  Much appreciated.

**Comment by atiweb** [comment] 2020-02-21 15:50
Hand on it!! Or better said.. Silicon tech on it!!! lolol

**Comment by atiweb** [comment] 2020-02-21 16:24
Test finished for InterProScan-5.39-77.0. All fine.
funannotate iprscan -i test.proteins.fasta -n 100 -o testOKOKOK.funannotate.xml --debug --method local --cpus 7 --iprscan_path /mnt/sdb/funannotate/interproscan/interproscan-5.39-77.0/interproscan.sh
Running InterProScan5 on 295 proteins
Important: you need to manually configure your interproscan.properties file for embedded workers.
Will try to launch 7 interproscan processes, adjust -c,--cpus for your system
InterProScan5 search has completed successfully!
Results are here: testOKOKOK.funannotate.xml

[test_results.zip](https://github.com/nextgenusfs/funannotate/files/4236988/test_results.zip)

**Comment by nextgenusfs** [comment] 2020-02-21 18:21
Great thanks @atiweb.  I'll push these commits to a new release quickly tonight and then update the conda recipe.  I guess I lied that 1.7.3 would be last release before python3 -- but I think better to get this released as there will be more issues arising with py3 conversion and I don't want to sit on these fixes until those issues are resolved.

**Closed** 2021-04-17 21:52 UTC
